// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:5ccc31fa-1963-4dea-a3ea-e92b81c96d5d",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_LOfD3MPHt",
    "aws_user_pools_web_client_id": "nnr2d094dmqojficmsuh92lj4"
};


export default awsmobile;
